export const LOADING_PAGES = "LOADING_PAGES";
export const GET_ALL_PAGES_SUCCESS = "GET_ALL_PAGES_SUCCESS";
export const GET_ALL_PAGES_FAIL = "GET_ALL_PAGES_FAIL";

export const ADD_NEW_PAGES_SUCCESS = "ADD_NEW_PAGES_SUCCESS";
export const ADD_NEW_PAGES_FAIL = "ADD_NEW_PAGES_FAIL";

export const GET_ONE_PAGE_SUCCESS = "GET_ONE_PAGE_SUCCESS";
export const GET_ONE_PAGE_FAIL = "GET_ONE_PAGE_FAIL";

export const EDIT_PAGE_SUCCESS = "EDIT_PAGE_SUCCESS";
export const EDIT_PAGE_FAIL = "EDIT_PAGE_FAIL";

export const MAKE_CURRENT_EMPTY = "MAKE_CURRENT_EMPTY";
